 
export const SET_COURSE = 'SET_COURSE'
export const SET_FORM_COURSE = 'SET_COURSE_STUDENT'



export const ADD_ROW_STUDENT = 'ADD_ROW_STUDENT'

//type action api student
export const ADD_STUDENT = 'ADD_STUDENT';
export const ADD_STUDENT_SUCCESS = 'ADD_STUDENT_SUCCESS';
export const ADD_STUDENT_FAILED = 'ADD_STUDENT_FAILED';

export const UPDATE_STUDENT = 'UPDATE_STUDENT';
export const UPDATE_STUDENT_FAILED = 'UPDATE_STUDENT_FAILED'
export const UPDATE_STUDENT_SUCCESS = 'UPDATE_STUDENT_SUCCESS'

export const DELETE_STUDENT = 'DELETE_STUDENT'
export const DELETE_STUDENT_FAILED = 'DELETE_STUDENT_FAILED'
export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS'

export const GET_STUDENTS_REQUEST = 'GET_STUDENTS_REQUEST'
export const RECEIVE_STUDENT_SUCCESS = 'RECEIVE_STUDENT_SUCCESS'
export const RECEIVE_STUDENT_FAILED = 'RECEIVE_STUDENT_FAILED'
export const GET_STUDENT_DETAIL_REQUEST = 'GET_STUDENT_DETAIL_REQUEST'

export const UPDATE_ENROL_STUDENT = 'UPDATE_ENROL_STUDENT'
export const UPDATE_ENROL_STUDENT_SUCCESS = 'UPDATE_ENROL_STUDENT_SUCCESS'
export const UPDATE_ENROL_STUDENT_FAILED = 'UPDATE_ENROL_STUDENT_FAILED'
 

//type action api course
export const ADD_COURSE = 'ADD_COURSE';
export const ADD_COURSE_SUCCESS = 'ADD_COURSE_SUCCESS';
export const ADD_COURSE_FAILED = 'ADD_COURSE_FAILED';

export const UPDATE_COURSE = 'UPDATE_COURSE';
export const UPDATE_COURSE_FAILED = 'UPDATE_COURSE_FAILED'
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS'

export const DELETE_COURSE = 'DELETE_COURSE'
export const DELETE_COURSE_FAILED = 'DELETE_COURSE_FAILED'
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS'

export const GET_COURSES_REQUEST = 'GET_COURSES_REQUEST' 
export const RECEIVE_COURSE_SUCCESS = 'RECEIVE_COURSE_SUCCESS'
export const RECEIVE_COURSE_FAILED = 'RECEIVE_COURSE_FAILED'

// type action app

export const ADD_EVENT = 'ADD_EVENT';
 

