export const ADD_STUDENT = 'ADD_STUDENT'
export const DELETE_STUDENT = 'DELETE_STUDENT'
export const UPDATE_STUDENT = 'UPDATE_STUDENT'
export const SET_STUDENT = 'SET_STUDENT'
export const SET_FORM_STUDENT = 'SET_FORM_STUDENT'
export const SET_COURSE = 'SET_COURSE'
export const SET_FORM_COURSE = 'SET_COURSE_STUDENT'



export const GET_STUDENTS_REQUEST = 'GET_STUDENTS_REQUEST' 
export const RECEIVE_STUDENT_SUCCESS = 'RECEIVE_STUDENT_SUCCESS'
export const RECEIVE_STUDENT_FAILED = 'RECEIVE_STUDENT_FAILED' 