 
export const SET_COURSE = 'SET_COURSE'
export const SET_FORM_COURSE = 'SET_COURSE_STUDENT'



export const ADD_ROW_STUDENT = 'ADD_ROW_STUDENT'

//type action api
export const ADD_STUDENT = 'ADD_STUDENT';
export const ADD_STUDENT_SUCCESS = 'ADD_STUDENT_SUCCESS';
export const ADD_STUDENT_FAILED = 'ADD_STUDENT_FAILED';

export const UPDATE_STUDENT = 'UPDATE_STUDENT';
export const UPDATE_STUDENT_FAILED = 'UPDATE_STUDENT_FAILED'
export const UPDATE_STUDENT_SUCCESS = 'UPDATE_STUDENT_SUCCESS'

export const DELETE_STUDENT = 'DELETE_STUDENT'
export const DELETE_STUDENT_FAILED = 'DELETE_STUDENT_FAILED'
export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS'

export const GET_STUDENTS_REQUEST = 'GET_STUDENTS_REQUEST' 
export const RECEIVE_STUDENT_SUCCESS = 'RECEIVE_STUDENT_SUCCESS'
export const RECEIVE_STUDENT_FAILED = 'RECEIVE_STUDENT_FAILED' 

// type action app

export const ADD_EVENT = 'ADD_EVENT';
 

